kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-allowlist
data:
  metrics_list.yaml: |
    names:
      - :node_memory_MemAvailable_bytes:sum
      - apiserver_request_total
      - cluster:capacity_cpu_cores:sum
      - cluster:capacity_memory_bytes:sum
      - container_cpu_cfs_periods_total
      - container_cpu_cfs_throttled_periods_total
      - container_cpu_usage_seconds_total
      - container_network_receive_bytes_total
      - container_network_receive_packets_dropped_total
      - container_network_receive_packets_total
      - container_network_transmit_bytes_total
      - container_network_transmit_packets_dropped_total
      - container_network_transmit_packets_total
      - go_goroutines
      - instance:node_cpu_utilisation:rate1m
      - instance:node_load1_per_cpu:ratio
      - instance:node_memory_utilisation:ratio
      - instance:node_network_receive_bytes_excluding_lo:rate1m
      - instance:node_network_receive_drop_excluding_lo:rate1m
      - instance:node_network_transmit_bytes_excluding_lo:rate1m
      - instance:node_network_transmit_drop_excluding_lo:rate1m
      - instance:node_num_cpu:sum
      - instance:node_vmstat_pgmajfault:rate1m
      - instance_device:node_disk_io_time_seconds:rate1m
      - instance_device:node_disk_io_time_weighted_seconds:rate1m
      - kube_node_status_allocatable_cpu_cores
      - kube_node_status_allocatable_memory_bytes
      - kube_pod_container_resource_limits_cpu_cores
      - kube_pod_container_resource_limits_memory_bytes
      - kube_pod_container_resource_requests_cpu_cores
      - kube_pod_container_resource_requests_memory_bytes
      - kube_pod_info
      - kube_pod_owner
      - kube_resourcequota
      - kubelet_volume_stats_available_bytes
      - kubelet_volume_stats_capacity_bytes
      - mixin_pod_workload
      - namespace_workload_pod:kube_pod_owner:relabel
      - node_cpu_seconds_total
      - node_filesystem_avail_bytes
      - node_filesystem_size_bytes
      - node_memory_MemAvailable_bytes
      - node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
      - node_namespace_pod_container:container_memory_cache
      - node_namespace_pod_container:container_memory_rss
      - node_namespace_pod_container:container_memory_swap
      - node_namespace_pod_container:container_memory_working_set_bytes
      - node_netstat_Tcp_OutSegs
      - node_netstat_Tcp_RetransSegs
      - node_netstat_TcpExt_TCPSynRetrans
      - process_cpu_seconds_total
      - process_resident_memory_bytes
      - up
      - workqueue_adds_total
      - workqueue_depth
    matches:
      - __name__="apiserver_request_duration_seconds_bucket",job="apiserver",verb!="WATCH"
      - __name__="workqueue_queue_duration_seconds_bucket",job="apiserver"
      - __name__="container_memory_cache",container!=""
      - __name__="container_memory_rss",container!=""
      - __name__="container_memory_swap",container!=""
      - __name__="container_memory_working_set_bytes",container!=""
    renames:
      mixin_pod_workload: namespace_workload_pod:kube_pod_owner:relabel, 
      namespace:kube_pod_container_resource_requests_cpu_cores:sum: namespace_cpu:kube_pod_container_resource_requests:sum